### ISSUE TITLE
Library does not compile: error in Microsoft Visual Studio Professional 2015

### ISSUE THREAD

**Issue by gutwinski** [hnkb/nlohmann-json-nuget#1]
After adding the package to my new project, I created the following very basic application using the library:

```
// ConsoleApplication1.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <nlohmann\json.hpp>


int main()
{
    return 0;
}
```
However, I cannot compile the program and get the following compiler errors:

- C2146	syntax error: missing '>' before identifier 'iterator_category'	4290
- C2893	Failed to specialize function template 'unknown-type std::begin(_Container &)'	4290
- C2893	Failed to specialize function template 'unknown-type std::begin(const _Container &)'	4290
- C2131	expression did not evaluate to a constant	2235
- C2784	'_Ty *std::begin(_Ty (&)[_Size]) noexcept': could not deduce template argument for '_Ty (&)[_Size]' from 'add_rvalue_reference<const ContiguousContainer>::type'	4290
- C2784	'_Ty *std::begin(std::valarray<_Ty> &)': could not deduce template argument for 'std::valarray<_Ty> &' from 'add_rvalue_reference<const ContiguousContainer>::type'	4290
- C4579	'nlohmann::detail::static_const<nlohmann::detail::to_json_fn>::value': in-class initialization for type 'const T' is not yet implemented; static member will remain uninitialized at runtime but use in constant-expressions is supported	2235
- C4579	'nlohmann::detail::static_const<nlohmann::detail::from_json_fn>::value': in-class initialization for type 'const T' is not yet implemented; static member will remain uninitialized at runtime but use in constant-expressions is supported	2235
- C2039	'iterator_category': is not a member of 'nlohmann::detail::iterator_traits<unknown-type,void>'	4290
- C2784	'const _Ty *std::begin(const std::valarray<_Ty> &)': could not deduce template argument for 'const std::valarray<_Ty> &' from 'add_rvalue_reference<const ContiguousContainer>::type'	4290
- C2784	'const _Elem *std::begin(std::initializer_list<_Elem>) noexcept': could not deduce template argument for 'std::initializer_list<_Elem>' from 'add_rvalue_reference<const ContiguousContainer>::type'	4290

I would very much appreciate your support.

Thanks,
Andreas

**Comment by gutwinski** [comment]
I accidentally closed the subject myself and had to re-open it.

**Comment by hnkb** [comment]
JSON for Modern C++ requires a compiler with C++11 capabilities and from the error messages you have I suspect you are using a setup that probably does not have this support.

Please make sure you are not using an older platform toolset in your project settings and check that your compiler version matches [the minimum required specified in this list](https://github.com/nlohmann/json#supported-compilers). You can view your Visual Studio version by accessing *Help -> About Microsoft Visual Studio* from main menu.

I did test adding the library to a new project on a fresh install of Visual Studio Professional 2015 and could not reproduce the error messages you report, as everything was compiled successfully. So I suspect you probably are using an older compiler version that does not have support for C++11. Please also try updating your Visual Studio 2015 (to Update 3) if it is possible for you.

**Comment by gutwinski** [comment]
Updating Visual Studio to "update 3" did the trick. Thanks for your help!
