### ISSUE TITLE
Package for decomposed headers

### ISSUE THREAD

**Issue by igoloe** [hnkb/nlohmann-json-nuget#3]
Can you also provide a nuget package for `include/nlohmann` with latest version 3.10.0 ?

**Comment by acohenOT** [comment]
This has already been published: https://www.nuget.org/packages/nlohmann.json/

**Comment by igoloe** [comment]
Looking into the package, I only see the single header variant, therefore was requesting a non single header variant package.

**Comment by hnkb** [comment]
Sorry for the delay. Here is the new package: https://www.nuget.org/packages/nlohmann.json.decomposed/

Please let me know if there is any problem with it.
